spring.application.name=facturacion


spring.datasource.url=jdbc:postgresql://localhost:5434/facturacion
spring.datasource.username=postgres
spring.datasource.password=admin

# Lo demás se queda igual
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de RabbitMQ con tus credenciales
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin